(module standard-includes mzscheme
  (require (lib "macros/grammar.scm" "42") 
           (lib "macros/assembly.scm" "42")
           (lib "macros/util.scm" "42")
           (lib "util/helpers.scm" "42")
           (lib "util/globals.scm" "42")
           (lib "structures.scm" "42")
           (lib "exceptions.scm" "42")
           (lib "productions.scm" "42")
           (lib "debug.scm" "42"))
  
  (provide (all-from (lib "macros/grammar.scm" "42"))
           (all-from (lib "macros/assembly.scm" "42"))
           (all-from (lib "macros/util.scm" "42"))
           (all-from (lib "util/helpers.scm" "42"))
           (all-from (lib "util/globals.scm" "42"))
           (all-from (lib "structures.scm" "42"))
           (all-from (lib "exceptions.scm" "42"))
           (all-from (lib "productions.scm" "42"))
           (all-from (lib "debug.scm" "42")))
  )